# Generated by Django 5.1.1 on 2024-09-16 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_rename_name_course_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_instructor',
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.student'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.IntegerField(default=0)),
                ('courses', models.ManyToManyField(related_name='instructors', to='telegram_bot.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.teacher'),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
