# Generated by Django 5.1.1 on 2024-09-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_remove_interest_teachers_teacher_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
