# Generated by Django 5.1.1 on 2024-09-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_remove_teacher_interests_delete_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.teacher'),
        ),
    ]
