# Generated by Django 5.1.1 on 2024-09-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_alter_application_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.teacher'),
        ),
    ]
