# Generated by Django 5.1.1 on 2024-09-18 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0009_alter_application_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='custom_topic',
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.student'),
        ),
        migrations.AlterField(
            model_name='application',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.teacher'),
        ),
    ]
